version: '3.5'

services:
  app:
    build: .
    container_name: app
    volumes:
      - ./:/app
    working_dir: /app

  webserver:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
